[workspace]
members = [
    "campus_backend",
    "campus_mobile"
]
resolver = "2"

<<<<<<< HEAD
=======
[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde", "clock"] }
thiserror = "1"
async-trait = "0.1"
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
futures-util = "0.3"


[dependencies.sqlx]
version = "0.7"
features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "macros",
]
>>>>>>> c546200 (Activity moudle commit)
